// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsalgicY8bgSKfsYwLXTJOJOph_9AOYU8',
    appId: '1:142294469883:web:7ff38726b9357ac42a345e',
    messagingSenderId: '142294469883',
    projectId: 'fluttergrad-9c464',
    authDomain: 'fluttergrad-9c464.firebaseapp.com',
    storageBucket: 'fluttergrad-9c464.appspot.com',
    measurementId: 'G-Q42D33HQ37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVc3S8nDSKIhvTjRldEYp0hoNUoz9hQKc',
    appId: '1:142294469883:android:1c92315c04b4a00d2a345e',
    messagingSenderId: '142294469883',
    projectId: 'fluttergrad-9c464',
    storageBucket: 'fluttergrad-9c464.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIklKEKPHIFiKnHSu6a_T5PASfMuyxT7s',
    appId: '1:142294469883:ios:9eaadc0ac81d78582a345e',
    messagingSenderId: '142294469883',
    projectId: 'fluttergrad-9c464',
    storageBucket: 'fluttergrad-9c464.appspot.com',
    iosBundleId: 'com.example.omg',
  );
}
